language: node_js
node_js:
  - 10
after_success:
  - npm install -g rollup
  - npm run build
before_deploy:
  - cp ./package.json ./dist/package.json
  - cp ./README.md ./dist/README.md
  - cp ./LICENSE ./dist/LICENSE
  - cd dist
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    repo: BenBrewerBowman/react-use-object-state
